# Generated by Django 5.1.4 on 2024-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='face_encodings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='facedata',
            name='names',
            field=models.JSONField(default=list),
        ),
    ]
