// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TnVlON9vYtVpVIwE4sWqE0oYYcG8ITg',
    appId: '1:542076174546:android:e26558c6f1e6ef179a6d0b',
    messagingSenderId: '542076174546',
    projectId: 'flutter-auth-d4c78',
    storageBucket: 'flutter-auth-d4c78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqjbGLCgdFRcyLKtdhylA-JKsmuAP8caE',
    appId: '1:542076174546:ios:3cf41c3a8dc294c19a6d0b',
    messagingSenderId: '542076174546',
    projectId: 'flutter-auth-d4c78',
    storageBucket: 'flutter-auth-d4c78.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4garjgy-C7Ob7ImBO7YzdV57cU8Nd9mY',
    appId: '1:542076174546:web:941e6fd050cd9a799a6d0b',
    messagingSenderId: '542076174546',
    projectId: 'flutter-auth-d4c78',
    authDomain: 'flutter-auth-d4c78.firebaseapp.com',
    storageBucket: 'flutter-auth-d4c78.firebasestorage.app',
  );
}
